"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import type { PersonnelProfile } from "@/lib/types";
type Draft = { displayName: string; defaultRole: string; defaultPayAmount: string; isActive: boolean; displayOrder: string };
const blank: Draft = { displayName: "", defaultRole: "", defaultPayAmount: "0.00", isActive: true, displayOrder: "0" };
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
export function PersonnelDirectoryPage({ showSlug }: { showSlug: string }) {
 const [profiles,setProfiles]=useState<PersonnelProfile[]>([]),[adding,setAdding]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState<Draft>(blank),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const response=await fetch(`/api/admin/personnel-profiles?slug=${encodeURIComponent(showSlug)}`,{cache:"no-store"});const payload=await response.json() as {error?:string;profiles?:Array<PersonnelProfile&{default_pay_amount:number|string}>};if(!response.ok)throw new Error(payload.error??"Unable to load Personnel Directory.");setProfiles((payload.profiles??[]).map(p=>({...p,default_pay_amount:Number(p.default_pay_amount)||0})))},[showSlug]);
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Unable to load Personnel Directory."))},[load]);
 const edit=(p:PersonnelProfile)=>{setAdding(false);setEditing(p.id);setDraft({displayName:p.display_name,defaultRole:p.default_role??"",defaultPayAmount:p.default_pay_amount.toFixed(2),isActive:p.is_active,displayOrder:String(p.display_order)});setError(null)};
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{const response=await fetch(editing?`/api/admin/personnel-profiles/${editing}?slug=${encodeURIComponent(showSlug)}`:`/api/admin/personnel-profiles?slug=${encodeURIComponent(showSlug)}`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??"Unable to save personnel profile.");setAdding(false);setEditing(null);setDraft(blank);await load()}catch(c){setError(c instanceof Error?c.message:"Unable to save personnel profile.")}finally{setBusy(false)}}
 const form=(adding||editing)?<form onSubmit={submit} className="grid gap-3 rounded-2xl border border-stone-200 bg-stone-50 p-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Name<input required value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})} className="rounded-lg border p-2"/></label><label className="grid gap-1 text-sm font-semibold">Default role<input value={draft.defaultRole} onChange={e=>setDraft({...draft,defaultRole:e.target.value})} className="rounded-lg border p-2"/></label><label className="grid gap-1 text-sm font-semibold">Default pay<input required type="number" min="0" step=".01" value={draft.defaultPayAmount} onChange={e=>setDraft({...draft,defaultPayAmount:e.target.value})} className="rounded-lg border p-2"/></label><label className="grid gap-1 text-sm font-semibold">Display order<input required type="number" step="1" value={draft.displayOrder} onChange={e=>setDraft({...draft,displayOrder:e.target.value})} className="rounded-lg border p-2"/></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft({...draft,isActive:e.target.checked})}/>Active</label><div className="flex items-end gap-2"><button disabled={busy} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">{busy?"Saving…":editing?"Save changes":"Add person"}</button><button type="button" onClick={()=>{setAdding(false);setEditing(null);setDraft(blank)}} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancel</button></div></form>:null;
 return <main className="min-h-screen bg-stone-100 px-4 py-8 text-stone-900 sm:px-6"><div className="mx-auto grid max-w-5xl gap-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/admin/${encodeURIComponent(showSlug)}`} className="text-sm font-semibold text-emerald-800">← Back to show</Link><h1 className="mt-2 text-3xl font-semibold">Personnel Directory</h1><p className="mt-1 text-sm text-stone-600">Reusable defaults for future show personnel. Existing show pay records are unchanged.</p></div><button type="button" onClick={()=>{setAdding(true);setEditing(null);setDraft(blank)}} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">Add Person</button></div>{error?<div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>:null}{form}<div className="grid gap-3">{profiles.map(p=><article key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-stone-200 bg-white p-4"><div><div className="flex items-center gap-2"><h2 className="font-semibold">{p.display_name}</h2><span className={`rounded-full px-2 py-1 text-xs font-semibold ${p.is_active?"bg-emerald-100 text-emerald-800":"bg-stone-200 text-stone-700"}`}>{p.is_active?"Active":"Inactive"}</span></div><p className="text-sm text-stone-600">{p.default_role||"Role not set"} · {money(p.default_pay_amount)} · Order {p.display_order}</p></div><button type="button" onClick={()=>edit(p)} className="rounded-lg border px-3 py-2 text-sm font-semibold">{p.is_active?"Edit":"Edit / Reactivate"}</button></article>)}{profiles.length===0?<p className="rounded-xl border border-dashed p-5 text-sm text-stone-500">No recurring personnel profiles yet.</p>:null}</div></div></main>;
}
