"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { summarizeSponsorRsvps, type SponsorShowRsvp, type SponsorRsvpStatus } from "@/lib/sponsor-rsvp";

type Assignment = { sponsor_id: string; sponsor: { id: string; name: string; recognition_name: string | null; sponsor_code: string | null } | null };
export function SponsorRsvpAdminPanel({ showId, showSlug }: { showId: string; showSlug: string }) {
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [rsvps, setRsvps] = useState<SponsorShowRsvp[]>([]); const [filter, setFilter] = useState<"all" | SponsorRsvpStatus>("all"); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/admin/shows/${encodeURIComponent(showId)}/sponsor-rsvps?slug=${encodeURIComponent(showSlug)}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setAssignments(payload.assignments ?? []); setRsvps(payload.rsvps ?? []); }, [showId, showSlug]);
  useEffect(() => {
    // The state update occurs only after the asynchronous admin API response.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load().catch((caught) => setError(caught instanceof Error ? caught.message : "Unable to load Sponsor RSVPs."));
  }, [load]);
  const rows = useMemo(() => assignments.filter((item) => item.sponsor).map((item) => ({ assignment: item, rsvp: rsvps.find((rsvp) => rsvp.sponsor_id === item.sponsor_id) ?? null })).filter((row) => filter === "all" || (row.rsvp?.status ?? "pending") === filter), [assignments, filter, rsvps]);
  const summaryRows = assignments.map((item) => rsvps.find((rsvp) => rsvp.sponsor_id === item.sponsor_id) ?? { status: "pending" as const, guest_count: null }); const summary = summarizeSponsorRsvps(summaryRows);
  async function save(sponsorId: string, status: SponsorRsvpStatus, guestCount: number | null, note: string) { const response = await fetch(`/api/admin/shows/${encodeURIComponent(showId)}/sponsor-rsvps`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ slug: showSlug, sponsorId, status, guestCount, note }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error); return; } setRsvps((current) => [...current.filter((row) => row.sponsor_id !== sponsorId), payload.rsvp]); }
  return <section className="rounded-2xl border border-stone-200 bg-white p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-lg font-semibold">Sponsor RSVP</h3><p className="text-sm text-stone-600">Show-specific responses; tickets and seats remain unchanged.</p></div><label className="grid gap-1 text-sm font-semibold">Filter<select value={filter} onChange={(e) => setFilter(e.target.value as typeof filter)} className="rounded-lg border px-3 py-2"><option value="all">All</option><option value="pending">Pending</option><option value="attending">Attending</option><option value="not_attending">Not Attending</option></select></label></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["Sponsors attending", summary.attending],["Sponsor guests", summary.totalGuests],["Not attending", summary.notAttending],["Pending", summary.pending]].map(([label,value]) => <div key={label} className="rounded-xl bg-stone-100 p-3"><p className="text-xs font-semibold uppercase text-stone-500">{label}</p><p className="text-2xl font-bold">{value}</p></div>)}</div>{error ? <p className="mt-3 text-sm text-rose-700">{error}</p> : null}<div className="mt-4 grid gap-3">{rows.map(({ assignment, rsvp }) => <RsvpRow key={assignment.sponsor_id} assignment={assignment} rsvp={rsvp} onSave={save} />)}</div></section>;
}
function RsvpRow({ assignment, rsvp, onSave }: { assignment: Assignment; rsvp: SponsorShowRsvp | null; onSave: (id: string, status: SponsorRsvpStatus, count: number | null, note: string) => Promise<void> }) { const sponsor = assignment.sponsor!; const [status,setStatus]=useState<SponsorRsvpStatus>(rsvp?.status ?? "pending"); const [count,setCount]=useState(rsvp?.guest_count?.toString() ?? ""); const [note,setNote]=useState(rsvp?.note ?? ""); return <div className="grid gap-3 rounded-xl border border-stone-200 p-3 lg:grid-cols-[1fr_10rem_7rem_1fr_auto] lg:items-end"><div><p className="font-semibold">{sponsor.recognition_name || sponsor.name}</p>{sponsor.sponsor_code ? <button type="button" onClick={() => navigator.clipboard.writeText(sponsor.sponsor_code!)} className="text-sm font-bold tracking-widest text-emerald-700" title="Copy Sponsor ID">Sponsor ID: {sponsor.sponsor_code}</button> : <p className="text-sm text-amber-700">Sponsor ID pending migration</p>}{rsvp?.responded_at ? <p className="text-xs text-stone-500">Responded {new Date(rsvp.responded_at).toLocaleString()}</p> : null}</div><label className="grid gap-1 text-xs font-semibold">Status<select value={status} onChange={(e)=>setStatus(e.target.value as SponsorRsvpStatus)} className="rounded-lg border px-2 py-2"><option value="pending">Pending</option><option value="attending">Attending</option><option value="not_attending">Not Attending</option></select></label><label className="grid gap-1 text-xs font-semibold">Guests<input type="number" min={1} disabled={status!=="attending"} value={count} onChange={(e)=>setCount(e.target.value)} className="rounded-lg border px-2 py-2" /></label><label className="grid gap-1 text-xs font-semibold">Optional note<input value={note} onChange={(e)=>setNote(e.target.value)} className="rounded-lg border px-2 py-2" /></label><button type="button" onClick={()=>void onSave(sponsor.id,status,status==="attending"?Number(count):null,note)} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Save RSVP</button></div>; }
