import type { BatchVariableFieldType, PrintRecord } from "./types";

export const PRINT_STUDIO_VARIABLE_KEYS = [
  "event_name",
  "show_date",
  "show_time",
  "venue",
  "purchaser_name",
  "guest_name",
  "sponsor_name",
  "ticket_type",
  "seat",
  "section",
  "ticket_number",
] as const satisfies readonly BatchVariableFieldType[];

export type PrintStudioVariableKey = (typeof PRINT_STUDIO_VARIABLE_KEYS)[number];

export type PrintStudioVariableDefinition = {
  key: PrintStudioVariableKey;
  label: string;
  description: string;
  expectedSource: string;
};

export const PRINT_STUDIO_VARIABLE_DEFINITIONS: PrintStudioVariableDefinition[] = [
  {
    key: "event_name",
    label: "Event Name",
    description: "Public-facing event or show title printed on a ticket.",
    expectedSource: "StageFlow show.name",
  },
  {
    key: "show_date",
    label: "Show Date",
    description: "Display-ready show date. Adapters may format a raw show_date before assigning it.",
    expectedSource: "StageFlow show.show_date",
  },
  {
    key: "show_time",
    label: "Show Time",
    description: "Display-ready show start time.",
    expectedSource: "StageFlow show.show_start_time",
  },
  {
    key: "venue",
    label: "Venue",
    description: "Public venue name for the ticket.",
    expectedSource: "StageFlow show.venue",
  },
  {
    key: "purchaser_name",
    label: "Purchaser Name",
    description: "Ticket buyer, reserved-seat customer, comp recipient, or equivalent print-facing name.",
    expectedSource: "guest_name, customer_name, assignment.customer_name, or derived row.name",
  },
  {
    key: "guest_name",
    label: "Guest Name",
    description: "Guest performer, guest-list name, or comp guest name when distinct from purchaser.",
    expectedSource: "show_comp_tickets.guest_name or GuestProfile.name",
  },
  {
    key: "sponsor_name",
    label: "Sponsor Name",
    description: "Sponsor or business name used on sponsor-facing tickets.",
    expectedSource: "derived sponsorName, sponsor.sponsor.name, SponsorLibraryEntry.name, or business_name",
  },
  {
    key: "ticket_type",
    label: "Ticket Type",
    description: "Display-ready admission, comp, sponsor, guest, or template category label.",
    expectedSource: "show_comp_tickets.ticket_type or derived categoryLabel/admissionType/templateKind",
  },
  {
    key: "seat",
    label: "Seat",
    description: "Display-ready seat label, formatted reserved-seat label, GA marker, or comp seat label.",
    expectedSource: "seat_id, seatLabel, stubSeatLabel, or reservedSeats",
  },
  {
    key: "section",
    label: "Section",
    description: "Reserved seating section or display section label.",
    expectedSource: "ShowReservedSeatAssignment.section",
  },
  {
    key: "ticket_number",
    label: "Ticket Number",
    description: "Display-ready ticket identifier generated by Print Studio or adapted from existing print data.",
    expectedSource: "generated ticketNumber, order_id, source_ticket_id, or source_order_id",
  },
];

export function isPrintStudioVariableKey(value: string): value is PrintStudioVariableKey {
  return PRINT_STUDIO_VARIABLE_KEYS.includes(value as PrintStudioVariableKey);
}

export function createPrintRecord(values: Partial<Record<PrintStudioVariableKey, string>> & { id: string; displayName?: string }): PrintRecord {
  return values;
}
